version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  pgdata:

networks:
  devnet:
    driver: bridge
